version: "3.8"

services:
  binance-pump-alerts:
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: patbaumgartner/binance-pump-alerts:latest
    # image: brianleect/binance-pump-alerts:latest
    restart: "no"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_ALERT_CHAT_ID=${TELEGRAM_ALERT_CHAT_ID}
      - PUMP_EMOJI=${PUMP_EMOJI}
      - DUMP_EMOJI=${DUMP_EMOJI}
      - NO_OF_REPORTED_COINS=${NO_OF_REPORTED_COINS}
      - DEBUG=${DEBUG}
      - RESET_INTERVAL=${RESET_INTERVAL}
